# Generated by Django 5.1.2 on 2024-10-27 11:23

import furryfunnies.authors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[furryfunnies.authors.validators.exact_length], verbose_name='Passcode'),
        ),
    ]
